### ISSUE TITLE
"No such module" Error

### ISSUE THREAD

**Issue by RoBo-Inc** [finestructure/Arena#100]
Hi.
The tool is awesome, super helpful.
But it doesn't work anymore.
I always get the the "No such module" error, whatever I try.

**Comment by finestructure** [comment]
Hi @RoBo-Inc , thanks for the report. I'm using Arena pretty much every week and haven't noticed any problems. Could you be more specific what isn't working? What's the command you're trying and what is the error message? Which version of Arena, Xcode, macOS are you using?

**Comment by finestructure** [comment]
Closing this, please reopen if you have more info.
