### ISSUE TITLE
Errors when using a package supporting macCatalyst

### ISSUE THREAD

**Issue by capnslipp** [finestructure/Arena#101]
When attempting to use `arena` (version 1.3.0; latest in homebrew) with a package that has macCatalyst listed in its platforms (e.g. `platforms: [ .iOS(.v16), .macCatalyst(.v16), ],`), arena fails with error:

```
🔧 Resolving package dependencies…
Error: dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "platforms", intValue: nil), _JSONKey(stringValue: "Index 1", intValue: 1), CodingKeys(stringValue: "platformName", intValue: nil)], debugDescription: "Cannot initialize Name from invalid String value maccatalyst", underlyingError: nil))
```

**Comment by finestructure** [comment]
Which version of Arena are you using? This should have been fixed in version 1.3.1: https://github.com/finestructure/Arena/releases/tag/1.3.1

**Comment by capnslipp** [comment]
It looks like I have 1.3.0, via https://github.com/finestructure/homebrew-tap/blob/HEAD/arena.rb

```
> brew info arena                                                                                                                                                                                                                              
==> finestructure/tap/arena: stable 1.3.0
Describe your project
https://github.com/finestructure/Arena
/opt/homebrew/Cellar/arena/1.3.0 (5 files, 1.6MB) *
  Built from source on 2023-12-15 at 13:34:25
From: https://github.com/finestructure/homebrew-tap/blob/HEAD/arena.rb
```

**Comment by finestructure** [comment]
Ok, so that's expected. Can you try again with the latest version 1.3.4, please?

**Comment by capnslipp** [comment]
Works after upgrade to 1.3.4 (via brew).

Please consider merging https://github.com/finestructure/homebrew-tap/pull/2

**Comment by finestructure** [comment]
Oh, I hadn't realised this had drifted. Thanks for fixing that up, merged!
