### ISSUE TITLE
No such module error after building

### ISSUE THREAD

**Issue by vquach2404** [finestructure/Arena#102]
Continuing to get the `No such module` error despite following instructions and building to re-trigger the SPM package. 

Details:
- Xcode 15.2.0
- Arena 1.3.4

Also curious to understand what Arena is doing that allows playgrounds to use SPM.

**Comment by finestructure** [comment]
Thanks for the report, @vquach2404 . Which package are you seeing the problem with?

Arena creates a full Swift package under the hood with the package injected as a dependency and embeds it in a playground. That's why the result isn't a single playground file but an Xcode project.

**Comment by finestructure** [comment]
Closing this, please reopen if you have more info!
