### ISSUE TITLE
Problem opening a cloned project

### ISSUE THREAD

**Issue by joaolfp** [finestructure/Arena#104]
Hi, I'm using arena to test my library and I uploaded it to git but when I went to clone the project and opened playgrounds in Xcode it's not loaded the package, I'll leave a screenshot below

<img width="1352" alt="Captura de Tela 2024-06-13 às 11 33 32" src="https://github.com/finestructure/Arena/assets/36343338/13969626-dd7f-4194-9acd-255076040751">

**Arena Version:** 1.3.4
**Xcode:** 15.4.0

Could you tell me how I can open it again in xcode and install the package?

**Comment by finestructure** [comment]
Hi @joaolfp , what command did you run to generate the playground and with what version of Arena?

**Comment by joaolfp** [comment]
Hi @finestructure, I used this version and command

**Arena version:** 1.3.4
**Command:** arena heroesofcode/DataLife

**Comment by finestructure** [comment]
Seems to be working fine:

```
❯ arena heroesofcode/DataLife
➡️  Package: https://github.com/heroesofcode/DataLife @ from(1.5.0)
🔧 Resolving package dependencies…
📔 Libraries found: DataLife
✅ Created project in folder 'Arena-Playground'
~/Downloads took 9s
❯ arena --version
1.3.4
```

![CleanShot 2024-06-18 at 11 35 22@2x](https://github.com/finestructure/Arena/assets/65520/62051be9-e01c-404a-8789-b3dfd8bb64d3)

Could you explain in more detail what problem you're encountering?

**Comment by finestructure** [comment]
`arena` opens the playground automatically but if you want to open it manually, make sure you open the xcworkspace file:

![CleanShot 2024-06-18 at 11 37 28@2x](https://github.com/finestructure/Arena/assets/65520/1a51b9d4-a3bf-42ae-9385-796af0181023)

**Comment by joaolfp** [comment]
Now it worked for me, I was unsure about the xcworkspace file. It's just that I had ignored it to upload it to git and I thought there was a way to generate xcworkspace again.

Thanks @finestructure
