### ISSUE TITLE
Support for the Playgrounds app on macOS

### ISSUE THREAD

**Issue by MaxDesiatov** [finestructure/Arena#16]
None of the generated playgrounds can be opened in the [Playgrounds app for macOS](https://apps.apple.com/gb/app/swift-playgrounds/id1496833156?mt=12). I understand that those playgrounds could work after tweaking their settings manually, but I wasn't able to achieve that. It would be great if Arena generated a compatible playground automatically (possibly controlled with a command-line flag if needed).

**Comment by finestructure** [comment]
Ah, interesting idea - that should be quite possible. I’ll have a look at the “Playground for Mac” format.

**Comment by finestructure** [comment]
At first glance this should work but may be a bit ugly: https://simonfairbairn.com/swift-packages-swift-playgrounds/

The `Sources` folder doesn’t support subfolders, apparently. Would have to check out the dependency into `Sources` and flatten the hierarchy.

**Comment by finestructure** [comment]
I've just pushed a branch https://github.com/finestructure/Arena/tree/swift-pg-book which adds a `--book` flag. This creates a playground book (in addition to the existing playground project) that should work in the "Swift Playgrounds" app.

Example:

```
 $  arena ~/Projects/Parser -f --book
🔧  resolving package dependencies
📔  libraries found: Parser
📄  4 source files found
📙  created Playground Book in folder 'SPM-Playground'
✅  created project in folder 'SPM-Playground'
```

I've done some light testing and it did work but it'd be great if you could give it a spin and let me know how it goes! :)

**Comment by MaxDesiatov** [comment]
@finestructure works pretty well for me, so far tested on just one package, but it was all good. Just probably needs a warning (in `README.md`?) that the package doesn't need to be `import`ed as it's available in the playground directly.

**Comment by MaxDesiatov** [comment]
Thanks for the quick update by the way!

**Comment by finestructure** [comment]
Ah yes, good point about the import statement. Thanks for testing!
