### ISSUE TITLE
Failed for Squid

### ISSUE THREAD

**Issue by imyrvold** [finestructure/Arena#4]
I tried to create a Playground with package from `https://github.com/borchero/Squid.git`, but that failed:

Ivans-iMac:ElementsPlayground imyrvold$ spm-playground -d https://github.com/borchero/Squid.git
🔧  resolving package dependencies
error: ShellOut encountered an error
Status code: 1
Message: "error: the package dependency graph could not be resolved; unable to find any available tag for the following requirements:
    https://github.com/borchero/Squid.git @ 0.0.0..<1.0.0"
Output: "Fetching https://github.com/borchero/Squid.git"

**Comment by finestructure** [comment]
Yes, there’s currently a limitation with respect to getting a working revision - basically SPMPlayground is assuming `from:0.0.0` if you don’t supply any version info and that can fail if the package has no versions in `0.0.0..<1.0.0` (which `from:0.0.0` translated to).

Looking at the package, can you give `-d https://github.com/borchero/Squid.git@from:1.0.0` a try? That should do the trick :)

**Comment by imyrvold** [comment]
Yes, that did it 😀 Thanks!

**Comment by imyrvold** [comment]
But the import in MyPlayground always fails.

Even when I run `spm-playground -d https://github.com/finestructure/Gala` , and the Playground opens, the playground shows the following error when run (with just the `import Gala` in the playground page):

> error: MyPlayground.playground:1:8: error: no such module 'Gala'
import Gala

**Comment by finestructure** [comment]
Make sure you build first! Product -> Build

Xcode often doesn't properly build dependencies unless you manually kick it off.

**Comment by imyrvold** [comment]
Yes, I got it working now. Thanks again!

**Comment by finestructure** [comment]
I’ll go ahead and close this. Please give a shout if anything else is amiss!
