### ISSUE TITLE
Latest revision lookup seems to fail for some repos

### ISSUE THREAD

**Issue by finestructure** [finestructure/Arena#48]
> Hi,
>
>	I am just trying out Arena and get the following error:
>
> diggory@MBP-16 ~ % arena https://github.com/Peter-Schorn/Swift_Utilities.git
> ➡️  Package: https://github.com/Peter-Schorn/Swift_Utilities.git @ from(0.0.0)
> 🔧 Resolving package dependencies ...
> Error: ShellOut encountered an error
Status code: 1
Message: "error: because no versions of Swift_Utilities match the requirement 0.0.0..<1.0.0 and root depends on Swift_Utilities 0.0.0..<1.0.0, version solving failed."
Output: "Fetching https://github.com/Peter-Schorn/Swift_Utilities.git"
diggory@MBP-16 ~ % arena --version                                          
0.15.3
>
>
>It looks as if the package it’s trying to get has tags that range from 1.0.0 to 1.4.1 but it’s failing because arena is looking for a tagged version between 0.0.0 and less than 1.0.0. Is that right?
Is this a bug?
>
>I can work around it by specifying the latest tagged version:
>
>diggory@MBP-16 ~ % arena https://github.com/Peter-Schorn/Swift_Utilities@from:1.4.1
➡️  Package: https://github.com/Peter-Schorn/Swift_Utilities @ from(1.4.1)
🔧 Resolving package dependencies ...
📔 Libraries found: Utilities
🔨 Building package dependencies ...
✅ Created project in folder 'Arena-Playground'

**Comment by finestructure** [comment]
Mmmm

```
 ~/Downloads  http https://api.github.com/repos/Peter-Schorn/Swift_Utilities/releases/latest
HTTP/1.1 404 Not Found
Content-Length: 119
X-GitHub-Request-Id: C072:509B:158987D:18FF4C2:5E9D4E9D
X-Ratelimit-Limit: 60
X-Ratelimit-Remaining: 47
X-Ratelimit-Reset: 1587370480
access-control-allow-origin: *
access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset
content-encoding: gzip
content-security-policy: default-src 'none'
content-type: application/json; charset=utf-8
date: Mon, 20 Apr 2020 07:26:21 GMT
referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
server: GitHub.com
status: 404 Not Found
strict-transport-security: max-age=31536000; includeSubdomains; preload
vary: Accept-Encoding, Accept, X-Requested-With
x-content-type-options: nosniff
x-frame-options: deny
x-github-media-type: github.v3; format=json
x-xss-protection: 1; mode=block

{
    "documentation_url": "https://developer.github.com/v3/repos/releases/#get-the-latest-release",
    "message": "Not Found"
}
```

**Comment by finestructure** [comment]
It looks like the issue might be that @Peter-Schorn has tagged revisions but they're not actual releases. It's a bit confusing in Github and I've only recently noticed the difference myself.

Apparently Github lists tags under releases but they're not really releases that show up when querying the API. (I think, I'm not 100% sure.)

I'll see if I can get latest tags if I get a 404 from the latest release query.

**Comment by finestructure** [comment]
https://help.github.com/en/github/administering-a-repository/about-releases

**Comment by Peter-Schorn** [comment]
@finestructure 
I'm new to swift and still trying to figure out how the package manager works. I've tagged my revisions with version numbers, but how do I make them "actual releases"? What additional steps do I have to perform? Also, could this be related to an issue I occasionally experience where Xcode gives me a 'no such module` error after I import my package?

**Comment by finestructure** [comment]
Hi Peter!

It wasn't actually an issue on your end - sorry for tagging you in without giving more information :) SPM works fine with just tags, it was Arena's problem of only checking for releases.

Releases are a Github thing: You can promote a tag to be a release. If you've tagged something, you can click on the three little dots behind the tag and there should be a menu item "Make release". See the docs here for more info: https://help.github.com/en/github/administering-a-repository/about-releases

The Xcode error wouldn't have anything to do with that. That typically happens when the package hasn't been built yet. Select "Product" -> "Build" to make sure the package is built properly, that should fix that.
