### ISSUE TITLE
Cannot Build/Install via Homebrew on Mojave

### ISSUE THREAD

**Issue by tonyatoms** [finestructure/Arena#52]
`brew install finestructure/tap/area `

fails eventually with:
 
```
/private/tmp/arena-20200428-1896-u8jqtu/Arena-0.16.0: error: manifest parse error(s):
<unknown>:0: error: Swift does not support the SDK 'MacOSX10.14.sdk'
```

Mac OS version 10.14.6
Swift 5.1.3

This is not a showstopper for me personally as I was able to build and install on a Catalina MacBook and move the resulting playground/workspace to the Mojave computer and use it there successfully. I only mention this because the README's Compatibility section may need to be revised. (I don't know that Mojave compatibility is really important at this point?)

**Comment by finestructure** [comment]
Ah yes, I should state this in the README but Arena currently only supports macOS 10.15 and Xcode 11.4.

I don’t think that’s insurmountable but the problem is I have no 10.14 available for testing 😟

**Comment by finestructure** [comment]
Whoops, missed you whole last paragraph when reading that on the go :)

I've just updated the README and thanks for confirming that the playgrounds work on older revisions!
