### ISSUE TITLE
[feature request] ⌘+b automatically at first launch

### ISSUE THREAD

**Issue by robbiemu** [finestructure/Arena#55]
it's kinda a buttery smooth experience now! with the playground opening in xcode immediately after install, but I still have to use ⌘+b to build it before I can use my module. Is it possible to do that once for us so we can just immediately import our library and rejoice?

**Comment by finestructure** [comment]
Arena *is* actually issuing a build step to try and make that unnecessary:

```
🔨 Building package dependencies ...
```

For some reason though it doesn't always seem to take. The other issue is that when opening up the playground I find it's often on the wrong platform, or has selected an attached iOS device, even for macOS playground. So an automatic build wouldn't really help.

I'm unsure what the best way to deal with this is - trust me, I get annoyed by it as well :D

There must be a way to select the destination either by creating the appropriate key in the project file or by doing something post launch. Maybe it's AppleScriptable?

If you have any ideas, please let me know!

**Comment by finestructure** [comment]
Solving this build issue before opening up the playground would likely also solve the big problem I'm having with autocomplete. I almost always have to build and restart Xcode to get it to see the new symbols. If the build worked properly beforehand that might all just work.

**Comment by finestructure** [comment]
I've had to roll back the package building because it was causing issues (see #58 )

⌘+b might be here to stay for now...
