### ISSUE TITLE
Can't download arena using mint 

### ISSUE THREAD

**Issue by Valter4578** [finestructure/Arena#56]
I tried to install arena using mint. I wrote `$ mint install finestructure/arena` and it gave me this output: 

`🌱 Finding latest version of arena
🌱 Cloning arena 0.16.1
🌱 Resolving package
error: terminated(72): rvm_bin_flag= rvm_quiet_flag= rvm_ruby_make_install= LIBRARY_PATH=/usr/local/lib ITERM_SESSION_ID=w0t0p0:6EC70495-9B9C-4BF6-890E-79D0224DC82B LANG=ru_RU.UTF-8 rvm_niceness= TMPDIR=/var/folders/0c/dqw12czj0n70y_2nhk8jpt640000gp/T/ SPACESHIP_ROOT=/Users/maksimalekseev/.oh-my-zsh/custom/themes/spaceship-prompt rvm_sdk= LC_TERMINAL_VERSION=3.3.9 rvm_ruby_bits= LC_TERMINAL=iTerm2 rvm_docs_type= LSCOLORS=Gxfxcxdxbxegedabagacad rvm_gemstone_url= LESS=-R COLORTERM=truecolor PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/Users/maksimalekseev/.rvm/bin PAGER=less CPATH=/usr/local/include rvm_alias_expanded= __CF_USER_TEXT_ENCODING=0x1F6:0x7:0x31 rvm_bin_path=/Users/maksimalekseev/.rvm/bin TERM=xterm-256color USER=maksimalekseev rvm_version=1.29.9 (latest) TERM_SESSION_ID=w0t0p0:6EC70495-9B9C-4BF6-890E-79D0224DC82B rvm_ruby_make= rvm_proxy= rvm_gemstone_package_file= HOME=/Users/maksimalekseev rvm_silent_flag= COLORFGBG=15;0 rvm_pretty_print_flag= XPC_FLAGS=0x0 ITERM_PROFILE=Dark SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.8NtE59INjl/Listeners SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk _=/usr/bin/swift ZSH=/Users/maksimalekseev/.oh-my-zsh rvm_prefix=/Users/maksimalekseev XPC_SERVICE_NAME=0 rvm_script_name= rvm_only_path_flag= TERM_PROGRAM_VERSION=3.3.9 rvm_path=/Users/maksimalekseev/.rvm GOPATH=/Users/maksimalekseev/go TERM_PROGRAM=iTerm.app rvm_use_flag= PWD=/private/var/folders/0c/dqw12czj0n70y_2nhk8jpt640000gp/T/mint/github.com_finestructure_arena SHELL=/bin/zsh SHLVL=2 LOGNAME=maksimalekseev rvm_nightly_flag= rvm_hook= SPACESHIP_VERSION=3.11.2 rvm_ruby_mode= rvm_ruby_file= xcrun --sdk macosx --find xctest output:
    xcrun: error: unable to find utility "xctest", not a developer tool or in PATH
🌱 Encountered error during "swift package resolve". Use --verbose to see full output
🌱  Failed to resolve arena 0.16.1 with SPM`

**Comment by finestructure** [comment]
Mmm, looks like maybe you don't have the command line tools installed? Can you try running

```
xcode-select --install
```

and then give it another go?

Oh, and which version of Xcode/macOS are you on?

**Comment by Valter4578** [comment]
I have installed Xcode Version 11.4.1 (11E503a), Mac OS 10.15.4 and xcode-select version 2373.

**Comment by finestructure** [comment]
Mmm - but at least I didn't break it for everyone:

```
❯ mint install finestructure/arena
🌱  Finding latest version of arena
🌱  Cloning arena 0.16.1
🌱  Resolving package
🌱  Building package
🌱  Installed arena 0.16.1
🌱  An executable that was not installed by mint already exists at /usr/local/bin/arena that is symlinked to /usr/local/Cellar/arena/0.16.1/bin/arena.
Overwrite it with Mint's symlink? (y/n)
```

Can you try the brew install variant please to see if it's specific to mint or the compile step?

```
brew install finestructure/tap/arena
```

Also, are you on mint 0.12.0 as well?

**Comment by finestructure** [comment]
Actually, mine is outdated - downloading 0.14.2 now and retrying.

**Comment by finestructure** [comment]
That worked as well.

What does `xcode-select -p` show?

See also: https://forums.developer.apple.com/thread/126921

**Comment by Valter4578** [comment]
`xcode-select -p` shows 
`/Library/Developer/CommandLineTools`

**Comment by finestructure** [comment]
That’s doesn’t look right, can you try setting it to /Application/Xcode.app?

**Comment by finestructure** [comment]
Cleaning up - please re-open if you're still having issues!
