### ISSUE TITLE
Arena doesn't accept branch names with certain characters in them

### ISSUE THREAD

**Issue by aure** [finestructure/Arena#62]
Even when quoted:

```
arena https://github.com/AudioKit/AudioKit@branch:v5-develop
arena "https://github.com/AudioKit/AudioKit@branch:v5-develop"
arena https://github.com/AudioKit/AudioKit@branch:"v5-develop"
```
all give

Error: The value 'https://github.com/AudioKit/AudioKit@branch:v5-develop' is invalid for &lt;dependencies>

whereas

```
aure$ arena https://github.com/AudioKit/AudioKit@branch:arena
➡️  Package: https://github.com/AudioKit/AudioKit @ branch("arena")
```

builds the playground.

**Comment by finestructure** [comment]
Hi Aurelius, thanks for the bug report! Interestingly, it's not the hyphen - I forgot to add _numbers_ to the allowed characters 😅

**Comment by aure** [comment]
Thanks for addressing out so quickly!
