### ISSUE TITLE
Playgrounds do not recognise external dependencies with Xcode 12

### ISSUE THREAD

**Issue by finestructure** [finestructure/Arena#64]
Imported modules are flagged with "no such module", despite clearly building _something_. The exact same playground project works in Xcode 11.

I need to research how external dependencies are supposed to work when set up manually with Xcode 12. I suspect the project file format is different to what Arena is generating right now.

**Comment by DarthMike** [comment]
This seems to explain why, and has links to other articles (didn't read in detail though)
https://idoit.tech/en/2020/swift-package-in-xcode-playground/

**Comment by finestructure** [comment]
Oh interesting, thanks for the link, @DarthMike !

**Comment by ABridoux** [comment]
Hi! I just tried your tool with Xcode 12 after having watched this [WWDC20 session](https://developer.apple.com/videos/play/wwdc2020/10096) and it works fine when checking "Build Active Scheme". Before checking that box I had the "No such module" error. I post that here in case it might help.

![Screenschot- 18 30 09 0510-2020@2x](https://user-images.githubusercontent.com/24890675/95106481-dea74800-0738-11eb-9fe0-f67e4dbb0636.png)

**Comment by finestructure** [comment]
Oh, that's great news. There's a branch for Xcode 12 now as well where I've enabled "Build Active Scheme" and which cleans up a few things.

I wonder though if this fix might be better for other reasons. Thanks for the tip!
