### ISSUE TITLE
Is there anyway to use a package that includes a c module?

### ISSUE THREAD

**Issue by brucemontegani** [finestructure/Arena#73]

**Comment by finestructure** [comment]
Hi Bruce, is there a specific package you're asking about? Are you getting an error message?

**Comment by brucemontegani** [comment]
Yes.

It is the Yams package for YAML. It is a wrapper for the CYML library

It is located here: https://github.com/jpsim/Yams

Code: https://github.com/jpsim/Yams.git

Please note that it also doesn’t work with another package that includes a wrapper for C:

https://github.com/tanner0101/mustache.git

Bruce

**Comment by finestructure** [comment]
Which version of Arena did you try this with? I've tried it with 1.0.0-b2 (and Xcode 12.1) and despite complaining about `CYaml` it seems to be working:

<img width="1072" alt="Screenshot 2020-10-25 at 16 07 03" src="https://user-images.githubusercontent.com/65520/97110994-8088d780-16dc-11eb-8f2d-99c46ca011c7.png">

**Comment by brucemontegani** [comment]
Yes... that is the message I am getting. Since in can't recognize the Yams module I can't use it in playgroundsSent from my T-Mobile 4G LTE Device
-------- Original message --------From: "Sven A. Schmidt" <notifications@github.com> Date: 10/25/20  8:10 AM  (GMT-08:00) To: finestructure/Arena <Arena@noreply.github.com> Cc: Bruce Montegani <bruce@montegani.com>, Author <author@noreply.github.com> Subject: Re: [finestructure/Arena] Is there anyway to use a package that includes a c module? (#73) 
Which version of Arena did you try this with? I've tried it with 1.0.0-b2 and Yams and despite complaining about CYaml it seems to be working:

**Comment by finestructure** [comment]
On the contrary, it appears to be working and the message presumably can be ignored. Look at the results of the input on the right hand side of the screenshot: it _is_ executing the code successfully despite the error message.

**Comment by brucemontegani** [comment]
Ok... I will check it later today. Thanks for your help. I wonder why it thinks the module is missing?Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: "Sven A. Schmidt" <notifications@github.com> Date: 10/25/20  9:38 AM  (GMT-08:00) To: finestructure/Arena <Arena@noreply.github.com> Cc: Bruce Montegani <bruce@montegani.com>, Author <author@noreply.github.com> Subject: Re: [finestructure/Arena] Is there anyway to use a package that includes a c module? (#73) 
On the contrary, it appears to be working and the message presumably can be ignored. Look at the results of the input on the right hand side of the screenshot: it is executing the code successfully despite the error message.

**Comment by brucemontegani** [comment]
Hi,

Sorry, but it just doesn’t work the way I expected. I get no code completion for the Yams package which is one of the purposes of using Playgrounds. 

Bruce

**Comment by DandyLyons** [comment]
Strange. I have the same behavior as you @finestructure . CYaml is missing but the code is still compiling. (Code completion is intermittent, but that's common for my outdated mac.)

**Comment by finestructure** [comment]
Closing this for now. Please reopen if the problem persists.
