### ISSUE TITLE
Allow Packages to provide Arena with pre-filled sample code

### ISSUE THREAD

**Issue by davdroman** [finestructure/Arena#74]
First of all, fantastic project — and name!

I'd like to put forward the idea of Arena being able to read a designated Swift file from the Package directory and pre-fill the generated playground with it. The file could be specific to Arena (ArenaSample.swift) or something else, it's really down to flavor.

Let me know your thoughts.

**Comment by finestructure** [comment]
Hi David, thanks for your kind words!

That's certainly a great idea - if I may say so myself, because it's something I'm definitely planning to do :)
