### ISSUE TITLE
Installation via Homebrew?

### ISSUE THREAD

**Issue by MaxDesiatov** [finestructure/Arena#8]
Thanks for this great tool! I wonder if there's an easy way to make it installable via Homebrew, so that there's one step less to install: you wouldn't need to clone the repository.

**Comment by finestructure** [comment]
Yes, I should do that! It‘s no big deal to set up - thanks to your nudge I’ll hopefully get to it asap :)

**Comment by finestructure** [comment]
Hey @MaxDesiatov , I've just updated the README with the latest installation instructions.

SPMPlayground (now "Arena"!) can be installed via Homebrew now 🚀

I've also added instructions for mint, which it supported all along.

Note that the Homebrew support is currently build from source. I'll look into adding a binary install next to make that a bit faster 🏃‍♀️

If you find Arena useful, please help spread the word! :)
