### ISSUE TITLE
Wrapper package conflicts with any existing "Dependencies" target

### ISSUE THREAD

**Issue by mamouneyya** [finestructure/Arena#96]
This is a kinda hilarious issue, but if you try to add [PointFree's Dependencies](https://github.com/pointfreeco/swift-dependencies/blob/main/Package.swift#L15) package to a Playground using Arena, it will produce a broken setup since the wrapper package's `Dependencies` target conflicts with the `Dependencies` target coming from the swift-dependencies. 

<img width="932" alt="Screenshot 2023-09-24 at 3 19 13 PM" src="https://github.com/finestructure/Arena/assets/212818/74d98d27-21fc-494d-9a26-b0e454345573">

**Comment by finestructure** [comment]
Ha, nice one 😅

I'll have to see if I can conditionally change the name to avoid collisions or if I need to find a new, more obscure name...

Thanks for the report!
